#!/bin/bash
# Deploy helper — pushes the current branch to origin.
# Stage your files explicitly with `git add <files>` before running this.

set -e

echo "Deploying ChatDB..."

if [ ! -d ".git" ]; then
    echo "Error: not a git repository. Run from the project root."
    exit 1
fi

if git diff --cached --quiet; then
    echo "Nothing staged. Use 'git add <files>' to stage your changes first."
    exit 1
fi

git commit -m "deploy: update ChatDB"

if ! git remote get-url origin > /dev/null 2>&1; then
    echo "No remote set. Add one with:"
    echo "  git remote add origin <your-repo-url>"
    echo "  git push -u origin main"
    exit 1
fi

git push origin main

echo ""
echo "Pushed to GitHub. Next steps for Render:"
echo "1. Render will auto-deploy if connected to this repo."
echo "2. Ensure these environment variables are set in Render:"
echo "   - SECRET_KEY (auto-generated by Render)"
echo "   - HUGGINGFACE_API_KEY (optional)"
